### ISSUE TITLE
Question about model converting & license

### ISSUE THREAD

**Issue by Lime-Cakes** [divamgupta/stable-diffusion-tensorflow#11]
What is the license for the implementation? 

Also, can you release the script you used to convert the model? I wish to port finetuned models to this codebase. Thanks!

**Comment by divamgupta** [comment]
https://github.com/divamgupta/stable-diffusion-tensorflow/blob/c159c79c1d1e347733abe652578d3d625fe9af3f/notebooks/stable-diffusion-tf.ipynb

**Comment by Lime-Cakes** [comment]
Thanks! Didn't notice license were added.
