### ISSUE TITLE
Prompt is too long (should be < 77 tokens)

### ISSUE THREAD

**Issue by lawrencecchen** [divamgupta/stable-diffusion-tensorflow#18]
Is there any way to have longer prompts? (I'm a complete ML noob, would love to learn!)

**Comment by lawrencecchen** [comment]
<img width="665" alt="Screen Shot 2022-09-20 at 10 03 40 PM" src="https://user-images.githubusercontent.com/54008264/191418440-ec5b8b25-e93b-4bbf-9a8e-518644998f51.png">

Just read stable diffusion's source code and learned that the tokenizer also caps at 77 tokens, so this issue is moot. I would still love to know why this is the case though!

**Comment by SidJain1412** [comment]
@lawrencecchen this explains it:
https://github.com/divamgupta/stable-diffusion-tensorflow/issues/20#issuecomment-1253779733

> The clip-vit-large-patch14 (https://huggingface.co/openai/clip-vit-large-patch14) model used by SD can only handle sequences of 77 tokens. It works like that in the original pytorch implementation as well. Anything longer than that gets silently truncated.
