### ISSUE TITLE
Passing image through encoder and decoder yields shifted result

### ISSUE THREAD

**Issue by Lime-Cakes** [divamgupta/stable-diffusion-tensorflow#41]
After passing an image into encoder and straight to decoder, the image is shifted slightly. This seemed to happen at various different size. 

Here's a basic colab to reproduce the weird result. It's edited from img2img notebook linked on readme. 
https://colab.research.google.com/drive/1lwCF5vdys5U4u9skE_DFrK8ecUP8Pmnm?usp=sharing

**Comment by Lime-Cakes** [comment]
I believed I have found the problem. Encoder adds extra padding at certain layers. I'll create a pull request ASAP

**Comment by divamgupta** [comment]
Great. Looking fwd to your PR!
