### ISSUE TITLE
Negative prompts

### ISSUE THREAD

**Issue by Juvuzux** [divamgupta/stable-diffusion-tensorflow#48]
As implemented, is it currently possible to use negative prompts?

**Comment by ju-popov** [comment]
I think the negative prompt is not a diffusion feature, but rather added from the GUI-s that exist?

**Comment by jorgemcgomes** [comment]
The negative prompt is simply the prompt that is used for the "unconditional" generation in Classifier-Free Guidance.
In this implementation it is hardcoded to be an empty string (or rather, a sequence full of padding tokens, https://github.com/divamgupta/stable-diffusion-tensorflow/blob/master/stable_diffusion_tf/constants.py), which is how it was originally meant to be.

It wouldn't be that hard to change the implementation to support any arbitrary prompt to be used for the unconditional guidance.

**Comment by divamgupta** [comment]
If anyone could send a PR with a Coab example, that would be great.
