### ISSUE TITLE
How to use Inpainting function

### ISSUE THREAD

**Issue by a53769** [divamgupta/stable-diffusion-tensorflow#51]
I see, some codes had already written at stable_diffusion.py,  but if use input_mask param directly It cause a error in runtime.

**Comment by ShaunXZ** [comment]
The input_mask param is the path to your mask file and should be used together with input_image. The mask is a single-channel uint8 array with two dimensions.

Could you try this [colab](https://colab.research.google.com/drive/1Bf-bNmAdtQhPcYNyC-guu0uTu9MYYfLu) example and see if that works？
