### ISSUE TITLE
Apple M1 8GB Speed comparison using Python vs using DiffusionBee

### ISSUE THREAD

**Issue by enzyme69** [divamgupta/stable-diffusion-tensorflow#52]
I am not sure if I have installed the Python version correctly, but using DiffusionBee, I believe I am getting 3-4 minutes per image at default.

While with the python version running it's 10 minutes per image.

I was wondering if the tensorflow gpu is properly installed on my M1 iMac 8GB memory? How do I check?

**Comment by ju-popov** [comment]
Macbook Pro
RAM: 32 GB
CPU: M1 Pro (8 cores)
GPU: (14 cores)
Neural Engine: (16 cores)
1.06s per iteration for 512x512 pixels
so... 20 steps per image - 21.2 s
50 steps - 53s

**Comment by ju-popov** [comment]
Still, it don't seems like 10 minutes to me

**Comment by enzyme69** [comment]
Ok I might come back to this. Maybe I need to restart the system when running this.
